config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :subjects
  devise_for :users
  resources :answers
  resources :pictures
  resources :questions
  resources :question_sets do
    resources :questions do
      resources :distractors
    end
  end
  resources :quizzes
  resources :users
  resources :subjects
  resources :distractors

end

app/models/question_set.rb
class QuestionSet < ActiveRecord::Base
	belongs_to :subject
	belongs_to :editor, :class_name => "User"
	has_many :question_sets_quizzes
	has_many :quizzes, :through => :question_sets_quizzes
	has_many :questions
	accepts_nested_attributes_for :questions, :reject_if => :all_blank, :allow_destroy => true

	def to_s
	  content.html_safe
	end

#This is for the select to be more presentable
	def truncated_content
		id.to_s+" - "+content.truncate(50,{omission: '...'})
  end


	scope :visible, lambda { where(:visible => true)  }
	scope :invisible, lambda { where(:visible => false) }
	scope :locked, lambda { where(:locked => true)}
	scope :unlocked, lambda { where(:locked => false)}
	scope :sorted, lambda { order("question_sets.position ASC")  }
	scope :newest_fisrt, lambda { order("question_sets.created_at DESC") }

	# asugurarme de que esto busque por autor
	scope :search, lambda { |query|
	 where(["name LIKE ?", "%#{query}%"]) }

end

app/controllers/question_sets_controller.rb
class QuestionSetsController < ApplicationController
  before_action :set_question_set, only: [:show, :edit, :update, :destroy]

  def index
    @question_sets = QuestionSet.all
  end

  def show
    @question_set = QuestionSet.find(params[:id])
  end

  def new
    @question_set = QuestionSet.new()
    # @questions = @question_set.questions.build
    @question_set.questions.build
    @question_set.questions.each do |question|
      question.distractors.build
    end


  end
  # POST /question_sets
  # POST /question_setsjson
  def create
    @question_set = QuestionSet.new(question_set_params)
    if @question_set.save
      flash[:notice] = "QuestionSet created successfully"
      redirect_to(:action => 'index')
    else
      render("new")
    end
  end

  def edit
    @question_set = QuestionSet.find(params[:id])
  end

  def update
    @question_set = QuestionSet.find(params[:id])
    if @question_set.update_attributes(question_set_params)
      flash[:notice] = "QuestionSet updated successfully"
      redirect_to(:action => 'show', :id => @question_set.id)
    else
      render('edit')
    end
  end

  def delete
    @question_set = QuestionSet.find(params[:id])
  end

  def destroy
      question_set = QuestionSet.find(params[:id]).destroy
      flash[:notice] = "QuestionSet '#{question_set.content}' has been destroyed successfully"
      redirect_to(:action => 'index')
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question_set
      @question_set = QuestionSet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_set_params
      params.require(:question_set).permit(:subject_id, :user_id, :difficulty, :visible, :locked, :position, :content, :questions_attributes => [:id, :difficulty, :visible, :locked, :position,:content, :value, :_destroy, :distractors_attributes => [:id, :question_id, :option, :difficulty, :visible, :locked, :content, :right, :_destroy]])
    end

end

app/helpers/question_sets_helper.rb
module QuestionSetsHelper
end

app/views/question_sets/_form.html.erb
<%= nested_form_for @question_set, :html => { :class => "form-vertical question_set" } do |f| %>

<% if @question_set.errors.any? %>
<div id="error_expl" class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title"><%= pluralize(@question_set.errors.count, "error") %> prohibited this question_set from being saved:</h3>
  </div>
  <div class="panel-body">
    <ul>
      <% @question_set.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>
<div class="panel-heading">Question Set</div>
<div class="panel-body">
<%= render :partial => 'question_sets/question_set_stats', :locals => {:f => f} %>
  <div class="form-group">
    <%= f.label :content, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.cktext_area :content, :class => 'form-control', :rows => 3, :toolbar=>'emma4_basic' %>
    </div>
    <%=f.error_span(:content) %>
  </div>
</div>
<div class="panel panel-default">
<div class="panel-heading">Questions</div>
<%= render :partial => 'question_sets/questions_form', :locals => {:f => f} %>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
      question_sets_path, :class => 'btn btn-default' %>
    </div>
  </div>

  <% end %>
<%= nested_form_for @question_set do |f| %>


<% end %>

app/views/question_sets/_question_set_stats.html.erb
<div class="row">
  <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
    <div class="form-group">
      <%= f.label :difficulty, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.number_field :difficulty, :class => 'form-control', min: 0, max: 1.0, step: 0.1 %>
      </div>
      <div class="col-lg-2">
        <div class="progress">
              <div class="progress-bar" role="progressbar" aria-valuenow="<%= (@question_set.difficulty)*100 %>"
              aria-valuemin="0" aria-valuemax="100" style="width:<%= (@question_set.difficulty)*100 %>%">
              <%= @question_set.difficulty  %>
              </div>
        </div>
      </div>
      <%=f.error_span(:difficulty) %>
    </div>
  </div>
  <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1">
    <div class="form-group">
      <%= f.label :visible, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.check_box :visible, :class => 'form-control' %>
      </div>
      <%=f.error_span(:visible) %>
    </div>
  </div>
  <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1">
    <div class="form-group">
      <%= f.label :locked, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.check_box :locked, :class => 'form-control' %>
      </div>
      <%=f.error_span(:locked) %>
    </div>
  </div>

  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <div class="form-group">
      <%= f.label :subject, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.collection_select(:subject_id, Subject.all, :id, :content, {},{:size => 1, :selected => :subject_id, :class => 'form-control'}) %>
      </div>
      <%=f.error_span(:visible) %>
    </div>
  </div>
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <div class="form-group">
      <%= f.label :position, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.number_field :position, :class => 'form-control', min: 1, step: 1 %>
      </div>
      <%=f.error_span(:position) %>
    </div>
  </div>

</div>

app/views/question_sets/_questions_form.html.erb
<div class="panel-body">
  <% @question_set.questions.each do |question| %>
  <div class="form-group">
    <%= f.fields_for :questions, question do |q| %>
    <%= f.label "Question", :class => 'control-label col-lg-2' %>
    <div class="row">
      <div class="col-md-8" style="padding-right:20px; border-right: 1px solid #ccc;">
        <%= q.cktext_area :content, :class => 'form-control', :rows => 3 %>
        <% question.distractors.each do |distractor| %>
          <%= q.fields_for :distractors, distractor do |d| %>
            <%= d.cktext_area :content, :id => distractor %>
            <%= d.link_to_remove "Remove this distractor", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
            :class => 'btn btn-xs btn-danger'  %>
          <% end %>
        <% end %>
      </div>
      <div class="col-md-4">
        <div class="row">
          <div class="col-md-6">
            <%= q.label :difficulty, :class => 'control-label' %>
          </div>
          <div class="col-md-6">
            <%= q.number_field :difficulty, :class => 'form-control', min: 0, max: 1.0, step: 0.1 %>
          </div>
        </div>
        <div class='row'>
          <div class="col-md-6">
            <%= q.label :visible, :class => 'control-label' %>
          </div>
          <div class="col-md-6">
            <%= q.check_box :visible, :class => 'form-control' %>
          </div>
          <%=q.error_span(:visible) %>
        </div
        <div class="row">
          <%= q.link_to_remove "Remove this question", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
          :class => 'btn btn-xs btn-danger'  %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
<div class="row">
  <div class="col-lg-12">
    <p><%= f.link_to_add "Add question", :questions, :class => 'btn btn-xs btn-success'  %></p>
  </div>
</div>
<% end %>
</div>

app/views/question_sets/edit.html.erb
<%- model_class = QuestionSet -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/question_sets/index.html.erb
<% model_class = QuestionSet %>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:subject) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:difficulty) %></th>
      <th><%= model_class.human_attribute_name(:visible) %></th>
      <th><%= model_class.human_attribute_name(:locked) %></th>
      <th><%= model_class.human_attribute_name(:position) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th>Related questions</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @question_sets.each do |question_set| %>
      <tr>
        <td><%= link_to question_set.id, question_set_path(question_set) %></td>
        <td><%= question_set.subject_id %></td>
        <td><%= question_set.user_id %></td>
        <td><%= question_set.difficulty %></td>
        <td><%= question_set.visible %></td>
        <td><%= question_set.locked %></td>
        <td><%= question_set.position %></td>
        <td><%= question_set.content %></td>
        <td><%=l question_set.created_at %></td>
        <td><%= question_set.questions.count %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_question_set_path(question_set), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      question_set_path(question_set),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
      <tr>
          <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_question_set_path,
            :class => 'btn btn-primary' %>

app/views/question_sets/new.html.erb
<%- model_class = QuestionSet -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/question_sets/show.html.erb
<%- model_class = QuestionSet -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:subject_id) %>:</strong></dt>
  <dd><%= @question_set.subject_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @question_set.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:difficulty) %>:</strong></dt>
  <dd><%= @question_set.difficulty %></dd>
  <dt><strong><%= model_class.human_attribute_name(:visible) %>:</strong></dt>
  <dd><%= @question_set.visible %></dd>
  <dt><strong><%= model_class.human_attribute_name(:locked) %>:</strong></dt>
  <dd><%= @question_set.locked %></dd>
  <dt><strong><%= model_class.human_attribute_name(:position) %>:</strong></dt>
  <dd><%= @question_set.position %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @question_set.to_s %></dd>
</dl>
<dl class="dl-horizontal">
  <% @question_set.questions.each  do  |question|  %>
  <dt></dt>
  <dd><%= question.to_s %></dd>
  <dd><%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_question_path(question), :class => 'btn btn-default btn-xs' %></dd>
  <% end %>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              question_sets_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_question_set_path(@question_set), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              question_set_path(@question_set),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>