config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :subjects
  devise_for :users
  resources :answers
  resources :pictures
  resources :questions
  resources :question_sets do
    resources :questions do
      resources :distractors
    end
  end
  resources :quizzes
  resources :users
  resources :subjects
  resources :distractors

end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  mount_uploader :file_name, FileNameUploader # Tells rails to use this uploader for this model.
  validates :file_name, presence: true#, on: :create
  validates :description, presence: true
  validates :locked, exclusion: { in: [nil] }
  validates :in_line, exclusion: { in: [nil] }
  validates :visible, exclusion: { in: [nil] }


end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:user_id, :question_id, :size, :format, :additional_code, :description, :in_line, :visible, :locked, :file_name)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_for @picture, :html => { :class => "form-horizontal picture" } do |f| %>

  <% if @picture.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @picture.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :file_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :file_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:file_name) %>
  </div>
  <div class="form-group">
    <%= f.label :user_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:user_id) %>
  </div>
  <div class="form-group">
    <%= f.label :question_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :question_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:question_id) %>
  </div>
  <div class="form-group">
    <%= f.label :size, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :size, :class => 'form-control' %>
    </div>
    <%=f.error_span(:size) %>
  </div>
  <div class="form-group">
    <%= f.label :format, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :format, :class => 'form-control' %>
    </div>
    <%=f.error_span(:format) %>
  </div>
  <div class="form-group">
    <%= f.label :additional_code, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :additional_code, :class => 'form-control' %>
    </div>
    <%=f.error_span(:additional_code) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :in_line, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :in_line, :class => 'form-control' %>
    </div>
    <%=f.error_span(:in_line) %>
  </div>
  <div class="form-group">
    <%= f.label :visible, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :visible, :class => 'form-control' %>
    </div>
    <%=f.error_span(:visible) %>
  </div>
  <div class="form-group">
    <%= f.label :locked, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :locked, :class => 'form-control' %>
    </div>
    <%=f.error_span(:locked) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                pictures_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/pictures/edit.html.erb
<%- model_class = Picture -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pictures/index.html.erb
<%- model_class = Picture -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:file_name) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:question_id) %></th>
      <th><%= model_class.human_attribute_name(:size) %></th>
      <th><%= model_class.human_attribute_name(:format) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:in_line) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= link_to picture.id, picture_path(picture) %></td>
        <td><%= image_tag picture.file_name.thumb.url.to_s %></td>
        <td><%= picture.user_id %></td>
        <td><%= link_to truncate(picture.question.content, :length => 40, :omission => "..."), question_path(picture.question_id)%></td>
        <td><%= picture.size %></td>
        <td><%= picture.format %></td>
        <td><%= picture.description %></td>
        <td><%= picture.in_line ?  badge('No', :danger) : badge('Si', :success) %></td>
        <td><%=l picture.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_picture_path(picture), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      picture_path(picture),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_picture_path,
            :class => 'btn btn-primary' %>

app/views/pictures/new.html.erb
<%- model_class = Picture -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pictures/show.html.erb
<%- model_class = Picture -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<dl class="dl-horizontal">
  <%= image_tag @picture.file_name if @picture.file_name? %>
</dl>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @picture.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:question_id) %>:</strong></dt>
  <dd><%= @picture.question_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:size) %>:</strong></dt>
  <dd><%= @picture.size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:format) %>:</strong></dt>
  <dd><%= @picture.format %></dd>
  <dt><strong><%= model_class.human_attribute_name(:additional_code) %>:</strong></dt>
  <dd><%= @picture.additional_code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @picture.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:in_line) %>:</strong></dt>
  <dd><%= @picture.in_line %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              pictures_path, :class => 'btn btn-default'  %>
<%= link_to 'Back', url_for(:back) %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_picture_path(@picture), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              picture_path(@picture),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>